version: "3.8"

volumes:
  express_node_modules:

services:
  mariadb:
    image: "mariadb:10.11.6"
    container_name: "mariadb"
    working_dir: "/docker-entrypoint-initdb.d"
    volumes:
      - ./mariadb/:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    healthcheck: # TODO check more in detail what healthcheck times does (start_period, interval etc.)
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: 
        "always"

  express: # Not adding image-name here because it is local
    container_name: "express"
    build: "./"
    working_dir: "/express/app"
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      start_period: 5s
      interval: 5s
      timeout: 5s
    volumes:
      - "./app/:/express/app"
      - "express_node_modules:/express/app/node_modules"
    ports:
      - "1337:1337"
    command: npm run dev
    depends_on:
      mariadb:
        condition: service_healthy
    restart:
        "on-failure"
